### ISSUE TITLE
Please stop patching other plugins' code

### ISSUE THREAD

**Issue by NotNite** [TRPG0/BRC-NoHUD#2]
Hiya,

I'm the developer of Slop Crew. I found out your plugin patches other plugins (namely [patching](https://github.com/TRPG0/BRC-NoHUD/blob/main/mod/Patches/Speedometer.cs) [Speedometer](https://github.com/SGiygas/Speedometer) and [patching](https://github.com/TRPG0/BRC-NoHUD/blob/main/mod/Patches/AssociatedPlayer.cs) [Slop Crew](https://thunderstore.io/c/bomb-rush-cyberfunk/p/NotNet/SlopCrew/)) through Harmony. **Please do not do this.** You can disable these UI elements by using [Transform.Find](https://docs.unity3d.com/ScriptReference/Transform.Find.html) if you must, but please do not patch other plugin developers' code:

- Errors/bugs in your code (which probably wouldn't happen in this scenario, tbf) can cause issues for the other plugin developer, with notably confusing stacktraces
- Changes to their code will break your code, and the Slop Crew rewrite will certainly break this mod
- Because of hacking around the GameObject, your implementation of hiding Slop Crew nameplates is incorrect, which means that the community contributor star does not get hidden

Please, in the future, contact me somewhere (GitHub Issues, Reptile Hideout Discord server, Slop Crew Discord server) if you're going to be integrating my plugin into your plugin - while nothing bad has happened in this scenario, patching other people's code can cause headaches for both developers, and it shouldn't be encouraged. I can implement exposing part of the config through the Slop Crew API in 2.0, as a more proper solution.

Thanks!

**Comment by TRPG0** [comment]
That's fair. I'll fix it once I get home in a couple hours.

**Comment by TRPG0** [comment]
It's fixed now. Sorry for doing that.
